name: Check Answers

on:
  pull_request_target:
    types:
      - opened
      - synchronize

jobs:
  check-answers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- tests/challenge.test.js

      - name: Merge pull request
        if: ${{ success() }} # Only merge if the previous steps were successful
        run: |
          TOKEN=$GITHUB_TOKEN
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          API_URL="https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/merge"
          curl -X PUT -H "Authorization: Bearer $TOKEN" $API_URL
